import { Router } from 'express';
import authRoutes from './auth.routes.js';
import studentRoutes from './student.routes.js';
import teacherRoutes from './teacher.routes.js';
import courseRoutes from './course.routes.js';
import schoolRoutes from './school.routes.js';
import classroomRoutes from './classroom.routes.js';
import scheduleTemplateRoutes from './schedule-template.routes.js';
import groupRoutes from './group.routes.js';
import agreementRoutes from './agreement.routes.js';
import enrollmentRoutes from './enrollment.routes.js';
import gradeRoutes from './grade.routes.js';
import userRoutes from './user.routes.js';
import attendanceRoutes from './attendance.routes.js';
import studentPortalRoutes from './student-portal.routes.js';
import guardianPortalRoutes from './guardian-portal.routes.js';
import statsRoutes from './stats.routes.js';
import notificationRoutes from './notification.routes.js';
import systemSettingsRoutes from './system-settings.routes.js';

const router = Router();

router.use('/auth', authRoutes);
router.use('/students', studentRoutes);
router.use('/teachers', teacherRoutes);
router.use('/schools', schoolRoutes);
router.use('/courses', courseRoutes);
router.use('/groups', groupRoutes);
router.use('/classrooms', classroomRoutes);
router.use('/schedule-templates', scheduleTemplateRoutes);
router.use('/agreements', agreementRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/grades', gradeRoutes);
router.use('/users', userRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/student-portal', studentPortalRoutes);
router.use('/guardian-portal', guardianPortalRoutes);
router.use('/stats', statsRoutes);
router.use('/notifications', notificationRoutes);
router.use('/settings', systemSettingsRoutes);

export default router;
